# Generated by Django 4.2.20 on 2025-07-10 02:59

from django.conf import settings
import django.contrib.postgres.search
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business', models.CharField(blank=True, max_length=500, null=True)),
                ('first', models.CharField(blank=True, max_length=500, null=True)),
                ('last', models.CharField(blank=True, max_length=500, null=True)),
                ('street', models.CharField(blank=True, max_length=500, null=True)),
                ('address2', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_numb', models.CharField(max_length=10, unique=True)),
                ('event', models.CharField(blank=True, max_length=500, null=True)),
                ('location', models.CharField(blank=True, max_length=500, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('date', models.DateField()),
                ('due', models.DateField()),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid'), ('Partial', 'Partial')], default='Unpaid', max_length=20)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.client')),
            ],
            options={
                'ordering': ['invoice_numb'],
            },
        ),
        migrations.CreateModel(
            name='MileageRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, default=0.7, max_digits=5)),
            ],
            options={
                'verbose_name': 'Mileage Rate',
                'verbose_name_plural': 'Mileage Rates',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_cat', models.CharField(blank=True, max_length=500, null=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='finance.category')),
            ],
            options={
                'verbose_name_plural': 'Sub Categories',
                'ordering': ['sub_cat'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.invoice')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.service'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_type', models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense')], default='Expense', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('transaction', models.CharField(max_length=255)),
                ('tax', models.CharField(default='Yes', max_length=10)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('account', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField()),
                ('invoice_numb', models.CharField(blank=True, max_length=255, null=True)),
                ('transport_type', models.CharField(blank=True, choices=[('personal_vehicle', 'Personal Vehicle'), ('rental_car', 'Rental Car'), ('flight', 'Flight'), ('public_transport', 'Public Transport')], help_text='Used to identify if actual expenses apply', max_length=30, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.category')),
                ('sub_cat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.subcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Transactions',
                'ordering': ['date'],
                'indexes': [models.Index(fields=['date', 'trans_type'], name='finance_tra_date_e22f1b_idx'), models.Index(fields=['user', 'date'], name='finance_tra_user_id_3294c0_idx'), models.Index(fields=['category'], name='finance_tra_categor_bbdf49_idx'), models.Index(fields=['sub_cat'], name='finance_tra_sub_cat_01be50_idx'), models.Index(fields=['invoice_numb'], name='finance_tra_invoice_be4f0a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Miles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('begin', models.DecimalField(decimal_places=1, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('end', models.DecimalField(decimal_places=1, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('total', models.DecimalField(decimal_places=1, editable=False, max_digits=10, null=True)),
                ('invoice', models.CharField(blank=True, max_length=255, null=True)),
                ('tax', models.CharField(default='Yes', max_length=10, null=True)),
                ('job', models.CharField(blank=True, max_length=255, null=True)),
                ('vehicle', models.CharField(default='Lead Foot', max_length=255, null=True)),
                ('mileage_type', models.CharField(choices=[('Taxable', 'Taxable'), ('Reimbursed', 'Reimbursed')], default='Taxable', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Miles',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', 'date'], name='finance_mil_user_id_e82525_idx'), models.Index(fields=['mileage_type'], name='finance_mil_mileage_95a41d_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_numb'], name='finance_inv_invoice_21faaa_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['date'], name='finance_inv_date_1aaab4_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['due'], name='finance_inv_due_860b47_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['paid_date'], name='finance_inv_paid_da_03a9a9_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['client'], name='finance_inv_client__37a0c7_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['service'], name='finance_inv_service_6c695b_idx'),
        ),
    ]
